# Generated by Django 2.1.7 on 2019-03-23 11:19

import Interface.Interface
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('authoritySignal', models.BooleanField(default=False)),
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
            bases=(models.Model, Interface.Interface.CustomerInterface),
        ),
        migrations.CreateModel(
            name='PersonalInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNumber', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('birthday', models.DateField()),
                ('profession', models.CharField(max_length=20)),
                ('sex', models.BooleanField()),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('bust', models.FloatField()),
                ('waistline', models.FloatField()),
                ('hipline', models.FloatField()),
                ('shoulderwidth', models.FloatField()),
            ],
            bases=(models.Model, Interface.Interface.PersonalInformationInterface),
        ),
        migrations.AddField(
            model_name='customer',
            name='personalInformation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='UserLogin.PersonalInformation'),
        ),
    ]
