# Generated by Django 2.1.7 on 2019-03-23 15:15

import Interface.Interface
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('authoritySignal', models.BooleanField(default=False)),
                ('password', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, Interface.Interface.CustomerInterface),
        ),
        migrations.CreateModel(
            name='PersonalInformation',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('phoneNumber', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('birthday', models.DateField()),
                ('profession', models.CharField(max_length=20)),
                ('sex', models.BooleanField()),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('bust', models.FloatField()),
                ('waistline', models.FloatField()),
                ('hipline', models.FloatField()),
                ('shoulderwidth', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, Interface.Interface.PersonalInformationInterface),
        ),
    ]
