# Generated by Django 2.1.7 on 2019-03-23 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserLogin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinformation',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='birthday',
            field=models.DateField(default='1970-01-01'),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='bust',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='height',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='hipline',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='phoneNumber',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='sex',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='shoulderwidth',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='waistline',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='weight',
            field=models.FloatField(default=0),
        ),
    ]
