# Generated by Django 2.1.7 on 2019-03-23 14:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('UserLogin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinformation',
            name='customer',
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='username',
            field=models.CharField(default=datetime.datetime(2019, 3, 23, 14, 11, 16, 418915, tzinfo=utc), max_length=20, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
