# Generated by Django 2.1.7 on 2019-03-23 17:32

import Interface.Interface
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserLogin', '0002_auto_20190323_2321'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityQA',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('securityQ1', models.IntegerField(default=-1)),
                ('securityA1', models.CharField(max_length=50)),
                ('securityQ2', models.IntegerField(default=-1)),
                ('securityA2', models.CharField(max_length=50)),
                ('securityQ3', models.IntegerField(default=-1)),
                ('securityA3', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, Interface.Interface.SecurityQAInterface),
        ),
    ]
