SESSION_LOGINSTATUS_ONLINE = 'Online'
AUTHORITY_CUSTOMER = 'Customer'
AUTHORITY_ADMINISTRATOR = 'Administrator'
SESSION_LOGINSTATUS_OFFLINE = 'Offline'

SECURITY_QUESTION_LIST=['您初中班主任的名字是','您父亲的名字是','您母亲的名字是']
