# Generated by Django 2.2 on 2019-04-07 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('coursename', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('courseintroduction', models.CharField(default='', max_length=100)),
                ('courseprice', models.IntegerField(default=0, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('authoritySignal', models.BooleanField(default=False)),
                ('password', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PersonalInformation',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('phoneNumber', models.CharField(default='', max_length=20)),
                ('name', models.CharField(default='', max_length=20)),
                ('age', models.IntegerField(default=0)),
                ('birthday', models.DateField(default='1970-01-01')),
                ('profession', models.CharField(max_length=20)),
                ('sex', models.BooleanField(default=False)),
                ('height', models.FloatField(default=0)),
                ('weight', models.FloatField(default=0)),
                ('bust', models.FloatField(default=0)),
                ('waistline', models.FloatField(default=0)),
                ('hipline', models.FloatField(default=0)),
                ('shoulderwidth', models.FloatField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PhysicalAssessment',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('customer', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('caption', models.CharField(max_length=50)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SecurityQA',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('securityQ1', models.CharField(max_length=50)),
                ('securityA1', models.CharField(max_length=50)),
                ('securityQ2', models.CharField(max_length=50)),
                ('securityA2', models.CharField(max_length=50)),
                ('securityQ3', models.CharField(max_length=50)),
                ('securityA3', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
