# Generated by Django 2.2 on 2019-04-10 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyrecord',
            name='time',
            field=models.DateTimeField(null=True),
        ),
    ]
