# Generated by Django 2.2 on 2019-04-09 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyRecord',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('coursename', models.CharField(max_length=50)),
                ('amount', models.IntegerField(default=0)),
                ('time', models.DateTimeField()),
                ('pay_flag', models.BooleanField(default=False)),
            ],
        ),
    ]
