# Generated by Django 2.2 on 2019-05-22 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyrecord',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
