# Generated by Django 2.2 on 2019-04-09 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0002_buyrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='courseprice',
            field=models.IntegerField(default=0),
        ),
    ]
