# Generated by Django 2.2 on 2019-04-09 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0003_auto_20190409_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyrecord',
            name='valid',
            field=models.BooleanField(default=True),
        ),
    ]
